// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0GZBvhKYlGnGa68XUrBzFxmGaeH1E3po',
    appId: '1:734054227626:web:aaba16073c60b2765afad3',
    messagingSenderId: '734054227626',
    projectId: 'elective-project-1',
    authDomain: 'elective-project-1.firebaseapp.com',
    storageBucket: 'elective-project-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS-iGucjPrjFz548YuFMRjUsaOodaTuRo',
    appId: '1:734054227626:android:02dc0ee8b7ffec2d5afad3',
    messagingSenderId: '734054227626',
    projectId: 'elective-project-1',
    storageBucket: 'elective-project-1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8TMKss4qtCmbn9kONuAG6WnAQrCEAcXY',
    appId: '1:734054227626:ios:cffaf0914d0db1cf5afad3',
    messagingSenderId: '734054227626',
    projectId: 'elective-project-1',
    storageBucket: 'elective-project-1.firebasestorage.app',
    iosBundleId: 'com.example.kizzApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8TMKss4qtCmbn9kONuAG6WnAQrCEAcXY',
    appId: '1:734054227626:ios:cffaf0914d0db1cf5afad3',
    messagingSenderId: '734054227626',
    projectId: 'elective-project-1',
    storageBucket: 'elective-project-1.firebasestorage.app',
    iosBundleId: 'com.example.kizzApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0GZBvhKYlGnGa68XUrBzFxmGaeH1E3po',
    appId: '1:734054227626:web:c4c656729c170ef15afad3',
    messagingSenderId: '734054227626',
    projectId: 'elective-project-1',
    authDomain: 'elective-project-1.firebaseapp.com',
    storageBucket: 'elective-project-1.firebasestorage.app',
  );
}
